version: '3.8'
services:

  auth:
    container_name: auth
    image: auth:1.0
    restart: always
    build:
      context: ../AuthService
    environment:
      - PORT=4500
      - DB_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@authpostgres:5432/user
      - REDIS_URL=${REDIS_URL}
      - SECRET=${SECRET}
    depends_on:
      - authpostgres
      - redis
    links:
      - authpostgres
      - redis
    ports:
      - "4500:4500"

  authpostgres:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=user
    volumes:
      - ./db_library_auth:/var/lib/postgresql/data

  redis:
    image: redis:7.0.7-alpine
